#!/usr/bin/env zsh

if [[ "$(uname -m)" == "arm64" ]]; then
  export PATH="/opt/homebrew/bin:${PATH}" # arm64
else
  export PATH="/usr/local/homebrew/bin:${PATH}" # x86_64
fi

BREWPATH=''
if [ -f /usr/local/homebrew/bin/brew ]; then
  BREWPATH='/usr/local/homebrew/bin/brew' # x86_64
fi
if [ -f /opt/homebrew/bin/brew ]; then
  BREWPATH='/opt/homebrew/bin/brew' # arm64
fi

if [ -n "${BREWPATH}" ]; then
  eval "$("${BREWPATH}" shellenv)"
  REPO="$(brew --repository)"
  HB_CNF_HANDLER="${REPO}/Library/Taps/homebrew/homebrew-command-not-found/handler.sh"
  if [ -f "${HB_CNF_HANDLER}" ]; then
    . "${HB_CNF_HANDLER}"
  fi
fi
