# Git clone based workflow regression where the command executed is ./initialize.sh
# .github/workflows/curl-regression.yaml
name: Curl Regression

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # https://crontab.cronhub.io/

jobs:
  macos_build:
    name: Build test
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 16
        system:
          - os: macos-10.15
            target: x86_64-apple-darwin
        include:
          - system:
              os: [self-hosted, macOS, ARM64]
              target: aarch64-apple-darwin
            node_version: 16

    steps:
      - name: Set env
        id: set-env
        run: echo "CI=true" >> $GITHUB_ENV

      - name: Display the architecture
        shell: bash
        run: |
          arch

      - name: Check the CI environment variable
        shell: bash
        run: |
          [[ -z "${CI}" ]] && echo "Not running on CI" || echo "Running on CI"

      - name: Remove preinstalled brew packages
        run: |
          brew remove --force --ignore-dependencies $(brew list --formula)

      - name: Cache brew deps
        uses: actions/cache@v2
        with:
          # Paths to cache:
          # /usr/local/Homebrew - installation folder of Homebrew
          # /usr/local/Cellar - installation folder of Homebrew formulae
          # /usr/local/Frameworks, /usr/local/bin, /usr/local/opt - contain (links to) binaries installed by Homebrew formulae
          # /usr/local/lib/python3.8 - Python3 packages installation
          path: |
            /usr/local/Homebrew
            /usr/local/Cellar
            /usr/local/Frameworks
            /usr/local/bin
            /usr/local/opt
            /usr/local/lib/python3.8
            /opt/homebrew/
          key: macos-build-cache-${{ hashFiles('./setup.sh') }}

      - name: Run the script
        env:
          RUN_SETUP: true
        run: |
          bash -c "`curl -L https://git.io/dotfiles-m1`"
