# .github/workflows/push.yml

name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build_and_test:
    name: Test
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 16
        system:
          - os: macos-10.15
            target: x86_64-apple-darwin
        include:
          - system:
              os: [self-hosted, macOS, ARM64]
              target: aarch64-apple-darwin
            node_version: 16

    steps:
      - uses: actions/checkout@v2
        env:
          REPO: ${{github.workspace}}
          DOTFILES_REF: ${{github.sha}}
          SKIP_SLOW_DEPENDENCIES: "1"
          HOMEBREW_BUNDLE_BREW_SKIP: "node"

      - name: Display the architecture
        shell: bash
        run: |
          arch

      - name: Check the CI environment variable
        shell: bash
        run: |
          echo $([[ -z $(ENV.has_key?('CI')) ]] && echo "Running on CI" || echo "Not running on CI")

      # - name: Bootstrap
      #   shell: bash
      #   run: |
      #     ./setup.sh
