# .github/workflows/push.yml

on: [push]

name: CI

jobs:
  build_and_test:
    name: Test
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 16
        system:
          - os: macos-10.15
            target: x86_64-apple-darwin
            shell: zsh {0}
        include:
          - system:
              os: [self-hosted, macOS, ARM64]
              target: aarch64-apple-darwin
              shell: zsh {0}
            node_version: 16
    env:
      REPO: ${{github.workspace}}
      DOTFILES_REF: ${{github.sha}}
      SKIP_SLOW_DEPENDENCIES: "1"
      HOMEBREW_BUNDLE_BREW_SKIP: "node"

    steps:
      - uses: actions/checkout@master

      - name: Display the shell path
        run: |
          echo $ZSH_NAME $ZSH_VERSION

      - name: Display the architecture
        run: |
          echo arch

      - name: Display the environment variables and their values
        run: |
          print %ENV

      - name: Check the CI environment variable
        shell: bash
        run: |
          echo $([[ -z $(ENV.has_key?('CI')) ]] && echo "Running on CI" || echo "Not running on CI")
