# .github/workflows/push.yaml
name: MacOS Agent build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  # shellcheck:
  #   name: Check lint errors on scripts
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       shell: bash
  #   steps:
  #     - name: Checkout with submodules
  #       uses: actions/checkout@v2

  #     - name: Run ShellCheck
  #       # brew install shellcheck
  #       uses: ludeeus/action-shellcheck@master
  #       env:
  #         SHELLCHECK_OPTS: -e SC2059 -e SC2034 -e SC1090

  size-badge:
    name: Create Size Badge
    runs-on: ubuntu-latest
    steps:
      - id: size
        run: echo "##[set-output name=data;]$(du -sh . | sed 's/[^0-9a-zA-Z]//g')"

      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@master
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: size-badge.json
          label: 'Repo Size'
          message: ${{ steps.size.outputs.data }}
          color: green

  initialize_build:
    name: Local initialize test
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2

      - name: Size Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: size
          LABEL: 'Repo Size'
          STATUS: ${{ steps.size.outputs.data }}
          COLOR: red
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up script test
        run: |
          ./initialize.sh

  curl_build:
    name: Remote curl initialize test without repo download
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up script test
        run: |
          bash -c "`curl -L https://git.io/dotfiles-m1`"

  macos_build:
    name: Build test
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 16
        system:
          - os: macos-10.15
            target: x86_64-apple-darwin
        include:
          - system:
              os: [self-hosted, macOS, ARM64]
              target: aarch64-apple-darwin
            node_version: 16

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        env:
          REPO: ${{github.workspace}}
          DOTFILES_REF: ${{github.sha}}
          SKIP_SLOW_DEPENDENCIES: "1"
          HOMEBREW_BUNDLE_BREW_SKIP: "node"

      - name: Set env
        id: set-env
        run: echo "CI=true" >> $GITHUB_ENV

      - name: Display the architecture
        shell: bash
        run: |
          arch

      - name: Check the CI environment variable
        shell: bash
        run: |
          [[ -z "${CI}" ]] && echo "Not running on CI" || echo "Running on CI"


      # - name: Remove preinstalled brew packages
      #   run: |
      #     brew remove --force --ignore-dependencies $(brew list --formula)

      # - name: Cache brew deps
      #   uses: actions/cache@v2
      #   with:
      #     # Paths to cache:
      #     # /usr/local/Homebrew - installation folder of Homebrew
      #     # /usr/local/Cellar - installation folder of Homebrew formulae
      #     # /usr/local/Frameworks, /usr/local/bin, /usr/local/opt - contain (links to) binaries installed by Homebrew formulae
      #     # /usr/local/lib/python3.8 - Python3 packages installation
      #     path: |
      #       /usr/local/Homebrew
      #       /usr/local/Cellar
      #       /usr/local/Frameworks
      #       /usr/local/bin
      #       /usr/local/opt
      #       /usr/local/lib/python3.8
      #       /opt/homebrew/
      #     key: macos-build-cache-${{ hashFiles('./setup.sh') }}

      # - name: Set up builder
      #   run: |
      #     ./setup.sh
